# Build app always on push - LTS
# RUn tests - on LTS if push
#           - on matrix when want to create release

name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        nodejs: [ 14, 16, 18 ]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.nodejs }}
        cache: 'npm'

    - run: npm i
    - run: npm run print
      env:
        FOO: ${{ secrets.TEST_SECRET }}
        BAR: ${{ secrets.TEST_SECRET }}

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 14
        cache: 'npm'

    - run: npm i
    - run: npm run test
    - run: sleep 30

  metadata:
    runs-on: ubuntu-latest
    outputs:
      current_branch: ${{ steps.outputs.outputs.current_branch }}
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6
      - id: outputs
        run: | 
          echo "current_branch=${{ steps.branch-name.outputs.current_branch }}" >> "$GITHUB_OUTPUT"

  release:
    uses: ./.github/workflows/release.yml
    needs: [build, test]

  conditional:
    uses: ./.github/workflows/manual.yml
    needs: [metadata]
    if: needs.metadata.outputs.current_branch == 'test-conditional'
