# Build app always on push - LTS
# RUn tests - on LTS if push
#           - on matrix when want to create release

name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        nodejs: [ 14, 16, 18 ]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.nodejs }}
        cache: 'npm'

    - run: npm i
    - run: npm run print
      env:
        FOO: ${{ secrets.TEST_SECRET }}
        BAR: ${{ secrets.TEST_SECRET }}

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 14
        cache: 'npm'

    - run: npm i
    - run: npm run test
    - run: sleep 10

  metadata:
    runs-on: ubuntu-latest
    outputs:
      current_branch: ${{ steps.branch-name.outputs.current_branch }}
      pkg_version: ${{ steps.branch-name.outputs.pkg_version }}
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6
      - uses: actions/checkout@v3
      - name: Get package version
        id: package-version
        run: echo "pkg_version=$(jq -r '.version' package.json)" >> $GITHUB_ENV
      - name: Check if release for package version already exists
        id: release-exists
        run: |
          curl --fail --silent "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/tags/$(jq .version -r package.json)" && echo "release_exists=true" >> $GITHUB_ENV || echo "release_exists=false" >> $GITHUB_ENV
          echo "$GITHUB_ENV"
          cat "$GITHUB_ENV"
      
      - name: Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files_separator: " "
          files: |
            package.json
            CHANGELOG.md
      - name: Get changed Files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

          echo "changed"
          echo ${{ steps.changed-files.outputs.all_changed_files }}
          echo ${{ steps.release-exists.outputs.release_exists }}
        

  release:
    uses: ./.github/workflows/release.yml
    needs: [build, test]

  conditional:
    uses: ./.github/workflows/manual.yml
    needs: [build, test, metadata]
    if: |
      (needs.metadata.outputs.current_branch == 'main') ||
      (contains(${{ needs.metadata.outputs.package_version }}, 'alpha') && contains(github.event.head_commit.message, 'release alpha'))
