# Build app always on push - LTS
# RUn tests - on LTS if push
#           - on matrix when want to create release

name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        nodejs: [ 14, 16, 18 ]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.nodejs }}
        cache: 'npm'

    - run: npm i
    - run: npm run print
      env:
        FOO: ${{ secrets.TEST_SECRET }}
        BAR: ${{ secrets.TEST_SECRET }}

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 14
        cache: 'npm'

    - run: npm i
    - run: npm run test
    - run: sleep 30

  metadata:
    runs-on: ubuntu-latest
    outputs:
      current_branch: ${{ steps.outputs.outputs.output3 }}
      output3: ${{ steps.outputs.outputs.output3 }}
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6
      - id: outputs
        run: | 
          echo "current_branch=${{ steps.branch-name.outputs.current_branch }}" >> "$GITHUB_OUTPUT"
          echo "output3=${{ steps.branch-name.outputs.current_branch }}" >> "$GITHUB_OUTPUT"

  debug:
    runs-on: ubuntu-latest
    needs: [metadata]
    steps:
      - run: echo "${{ needs.metatada.outputs.current_branch }}"


  release:
    uses: ./.github/workflows/release.yml
    needs: [build, test]

  conditional:
    uses: ./.github/workflows/manual.yml
    needs: [build, test, metadata]
    if: needs.metatada.outputs.output3 == 'test-conditional'

  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: [job1, metadata]
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
          OUTPUT3: ${{needs.metadata.outputs.output3}}
        run: echo "$OUTPUT1 $OUTPUT2 $OUTPUT3"
      - run: echo ${{needs.metadata.outputs.output3}}
