name: Release

on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build passed, create release"
      - name: Checkout code
        uses: actions/checkout@v3
      - run: cat package.json
